### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by borysfranko11** [derhuerst/p2p-local-network-chat#1]
I am going to build chat app inside local network. So dont need hosting sever
Need your help

**Comment by derhuerst** [comment]
This package is a very minimal implementation or a chat and merely serves as a demo for how you might want to build a P2P chat via the local network. Browse through the source code to check what it is doing.

If you're looking for more sophisticated implementation, check out [cabal](https://github.com/cabal-club/cabal) (whole chat program with UI). If you're looking for libraries to put together, check out

- [`hyperdb`](https://github.com/mafintosh/hyperdb#readme) for storing the data
- [`airswarm`](https://github.com/mafintosh/airswarm#airswarm) for finding peers
- [`really-basic-chat-ui`](https://github.com/derhuerst/really-basic-chat-ui) for rendering command line chat UIs

**Comment by derhuerst** [comment]
Please reopen if you have more questions.

**Comment by rohanbd** [comment]
i Need A VPN Coustome Admin Panel For Manage User And Server ,

Admin Can Add Server

Panel Accepte All Protocol TCP / UDP/SSL/TLS/DNS

Reselller System Reseller Can Create Reseller And Also Can Create VPN ..

Specially We Need Cisco openconnect/AnyConnect VPN Using .

And user of panel connect to openconnect vpn apps


WhatsApp: +8801911946917

Telegram: +8801911946917

Mail: bkashguru@gmail.com
