### ISSUE TITLE
can't connect two peers

### ISSUE THREAD

**Issue by borysfranko11** [derhuerst/p2p-local-network-chat#2]
I tried to install this module on 2 computers and make it run.. 
But can not chat each other?
Can you give me guide how can i use this to build LAN p2p messenger ?
Thanks

**Comment by derhuerst** [comment]
Does peer A show a chat message of peer B?

**Comment by derhuerst** [comment]
`p2p-local-network-chat` uses [`airswarm`](https://github.com/mafintosh/airswarm#airswarm) to find peers, which in turn uses [`multicast-dns`](https://github.com/mafintosh/multicast-dns).

Make sure Multicast DNS is working on your network by checking if [Bonjour](https://en.wikipedia.org/wiki/Bonjour_(software))/[Avahi](https://en.wikipedia.org/wiki/Avahi_(software)) finds any devices, e.g. shared printers, AirPlay receivers. On macOS, you can use [Bonjour browser](https://itunes.apple.com/us/app/discovery-dns-sd-browser/id1381004916), on Linux, you can use [`avahi-browse`](https://itunes.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12).

**Comment by derhuerst** [comment]
Did you solve it?

**Comment by derhuerst** [comment]
Please reopen if you still have problems.
